services:
  ts:
    image: tailscale/tailscale:latest
    hostname: pastebin
    environment:
      - TS_AUTHKEY=tskey-client-blah
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/pastebin.json
    volumes:
      - ${PWD}/tailscale/state:/var/lib/tailscale
      - ${PWD}/tailscale/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module

    restart: unless-stopped

  pastebin:
    container_name: app
    image: ghcr.io/enchant97/hasty-paste:1
    restart: unless-stopped
    volumes:
      - pastedata:/app/data
    network_mode: service:ts

volumes:
  pastedata:
